[package]
name = "scaledslice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debug_plotter = {git = "https://github.com/toastmod/debug-plotter.git", default_features = false}
realfft = "3.0.1"
